// Opencode hook generator (v1.8.0-alpha.3+, Phase 4).
//
// Writes a plugin JS file at .opencode/plugins/aegis-keeper.js.
// Plugin hooks:
//   - tool.execute.before → policy gate (throws if block, aborts the tool)
//   - tool.execute.after  → per-edit append (fire-and-forget)
//   - session.end         → advisory summary
//
// The plugin file is owned by Aegis Spec — entire file is created/deleted.

import { existsSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';

const PLUGIN_REL = '.opencode/plugins/aegis-keeper.js';

function buildPlugin(runnerPath) {
  return `// Auto-generated by \`npx aegis add-hooks --engine opencode\`.
// Manages the Keeper queue and policy gate for Opencode.
// Removed by \`npx aegis remove-hooks --engine opencode\` or \`npx aegis uninstall\`.

import { spawn, spawnSync } from 'node:child_process';

const RUNNER = ${JSON.stringify(runnerPath)};

function invokeRunnerAsync(phase, payload) {
  const child = spawn('node', [RUNNER, '--phase', phase, '--engine', 'opencode', '--tool', payload?.tool ?? 'unknown'], {
    stdio: ['pipe', 'inherit', 'inherit'],
    detached: false,
  });
  try {
    child.stdin.write(JSON.stringify(payload ?? {}));
    child.stdin.end();
  } catch { /* swallow */ }
}

function invokeRunnerSync(phase, payload) {
  return spawnSync('node', [RUNNER, '--phase', phase, '--engine', 'opencode', '--tool', payload?.tool ?? 'unknown'], {
    input: JSON.stringify(payload ?? {}),
    encoding: 'utf8',
    env: { ...process.env, REVERSA_OPENCODE_PLUGIN: '1' },
  });
}

export default {
  'tool.execute.before': async ({ tool, input }) => {
    const r = invokeRunnerSync('pre', { tool, tool_input: input });
    if (r.status === 2) {
      let reason = 'Aegis Spec policy block';
      try {
        const parsed = JSON.parse((r.stdout ?? '').trim().split(/\\n/).pop());
        if (parsed && parsed.reason) reason = parsed.reason;
      } catch { /* ignore */ }
      throw new Error(reason);
    }
  },
  'tool.execute.after': async ({ tool, input, output }) => {
    invokeRunnerAsync('post', { tool, tool_input: input, output });
  },
  'session.end': async () => {
    invokeRunnerAsync('stop', {});
  },
};
`;
}

export default {
  id: 'opencode',
  name: 'Opencode',

  describe() {
    return 'Installs plugin .opencode/plugins/aegis-keeper.js (policy gate + queue + session.end)';
  },

  generate({ projectRoot, runnerPath }) {
    const target = join(projectRoot, PLUGIN_REL);
    return {
      files: [{ path: target, content: buildPlugin(runnerPath) }],
      summary: [
        `Will write to: ${PLUGIN_REL}`,
        `  Plugin hooks: tool.execute.before (policy gate, sync) + tool.execute.after (queue) + session.end (advisory).`,
      ].join('\n'),
    };
  },

  remove({ projectRoot }) {
    const target = join(projectRoot, PLUGIN_REL);
    const result = { removed: [], cleaned: [] };
    if (existsSync(target)) {
      try { unlinkSync(target); result.removed.push(target); }
      catch { /* swallow */ }
    }
    return result;
  },
};
